-- SEAWATER
minetest.register_node(":tides:seawater", {
	description = ("tides:seawater : still water"),
	drawtype = "liquid",
	waving = 3,
	tiles = {
		{
			name = "default_water_source_animated.png",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
		{
			name = "default_water_source_animated.png",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
	},
	use_texture_alpha = "blend",
	paramtype = "light",
	walkable = false,
	pointable = true,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drop = "",
	drowning = 1,
	liquid_range = 3,
	liquidtype = "source",
	liquid_alternative_flowing = "tides:wave",
	liquid_alternative_source = "tides:seawater",
	liquid_renewable = true,
	floodable = false,
	liquid_viscosity = 1,
	post_effect_color = {a = 103, r = 30, g = 30, b = 90},
	groups = {water = 3, liquid = 3, cools_lava = 1},
	--sounds = default.node_sound_water_defaults(),
})

minetest.register_node(":tides:wave", {
	description = ("tides:wave"),
	drawtype = "flowingliquid",
	waving = 3,
	tiles = {"default_water.png"},
	special_tiles = {
		{
			name = "default_water_flowing_animated.png^[colorize:#99f:100",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 0.5,
			},
		},
		{
			name = "default_water_flowing_animated.png^[colorize:#99f:100",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 0.5,
			},
		},
	},
	use_texture_alpha = "blend",
	paramtype = "light",
	paramtype2 = "flowingliquid",
	walkable = false,
	pointable = true,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drop = "",
	drowning = 1,
	liquidtype = "flowing",
	liquid_alternative_flowing = "tides:wave",
	liquid_alternative_source = "tides:seawater",
	liquid_renewable = false,
	floodable = true,
	liquid_viscosity = 1,
	post_effect_color = {a = 103, r = 30, g = 60, b = 90},
	groups = {water = 3, liquid = 3, not_in_creative_inventory = 0,
		cools_lava = 1},
	--sounds = default.node_sound_water_defaults(),
})

--SHOREWATER
minetest.register_node(":tides:shorewater", {
	description = ("tides:shorewater : makes tides go down"),
	drawtype = "liquid",
	waving = 3,
	tiles = {
		{
			name = "default_water_source_animated.png^[colorize:#fff:100",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
		{
			name = "default_water_source_animated.png^[colorize:#fff:100",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
	},
	use_texture_alpha = "blend",
	paramtype = "light",
	walkable = false,
	pointable = true,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drop = "",
	drowning = 1,
--	liquid_range = 1,
	liquidtype = "none",--"source",
--	liquid_alternative_flowing = "tides:wave",
--	liquid_alternative_source = "tides:shorewater",
	liquid_renewable = false,
	floodable = false,
	liquid_viscosity = 1,
	post_effect_color = {a = 103, r = 30, g = 30, b = 90},
	groups = {water = 3, liquid = 3, cools_lava = 1},
	--sounds = default.node_sound_water_defaults(),
})

-- OFFSHORE_WATER
minetest.register_node(":tides:offshore_water", {
	description = ("tides:offshore_water : make tides rise"),
	drawtype = "liquid",
	waving = 3,
	tiles = {
		{
			name = "default_water_source_animated.png^[colorize:#000:100",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
		{
			name = "default_water_source_animated.png^[colorize:#000:100",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
	},
	use_texture_alpha = "blend",
	paramtype = "light",
	walkable = false,
	pointable = true,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drop = "",
	drowning = 1,
--	liquid_range = 3,
	liquidtype = "none",
--	liquid_alternative_flowing = "tides:wave",
--	liquid_alternative_source = "tides:offshore_water",
	liquid_renewable = false,
	floodable = false,
	liquid_viscosity = 1,
	post_effect_color = {a = 103, r = 30, g = 30, b = 90},
	groups = {water = 3, liquid = 3, cools_lava = 1},
	--sounds = default.node_sound_water_defaults(),
})